/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MusiccollectionGUI.java
 *
 * Created on 12-Sep-2018, 15:53:24
 */
package musiccollectiongui;

import musiccollection_core.*;

/**
 *
 * @author Tony Chambers
 */
public class MusiccollectionGUI extends javax.swing.JFrame
{

    private MusicCollection_Coord musicCollection;

    /** Creates new form MusiccollectionGUI */
    public MusiccollectionGUI()
    {
        initComponents();
        musicCollection = new MusicCollection_Coord();
        displayAlbums();
    }

    private void resetTextValues()
    {
        addAlbumName.setText("");
        addAlbumArtist.setText("");
        addTrackName.setText("");
        addTrackArtist.setText("");
    }

    private void displayAlbums()
    {
        albumList.setListData(musicCollection.getAlbums());
        albumList.setSelectedIndex(0);
        getAlbumTracks();
    }

    private void addAlbum()
    {
        String albumName = addAlbumName.getText();
        String albumArtist = addAlbumArtist.getText();
        if (albumName.equals("") || albumArtist.equals(""))
        {
            outcomeArea.setText(
                    "Please make sure you have entered both an album name and an artist");
        }
        else
        {
            if (musicCollection.addAlbum(albumName, albumArtist))
            {
                outcomeArea.setText("Album successfully added");
                displayAlbums();
                resetTextValues();
            }
            else
            {
                outcomeArea.setText("Sorry, there has been a problem");
            }
        }

    }

    private void removeAlbum()
    {

        int dialogResult = optionPane.showConfirmDialog(null,
                "Do you want to remove track?", "Confirm",
                optionPane.YES_NO_OPTION, optionPane.QUESTION_MESSAGE);
        if (dialogResult == optionPane.YES_OPTION)
        {

            Album anAlbum = (Album) albumList.getSelectedValue();
            musicCollection.removeAllTracks(anAlbum);
            trackList.setListData(musicCollection.getAlbumTracks(anAlbum));
            musicCollection.removeAlbum(anAlbum);
            trackList.setSelectedIndex(0);
            displayAlbums();
        }

    }

    private void getAlbumTracks()
    {
        if (!albumList.isSelectionEmpty())
        {

            Album anAlbum = (Album) albumList.getSelectedValue();
            trackList.setListData(musicCollection.getAlbumTracks(anAlbum));
            trackList.setSelectedIndex(0);

        }

    }

    private void addTrack()
    {
        String addTrckName = addTrackName.getText();
        String addTrckArtist = addTrackArtist.getText();
        Album anAlbum = (Album) albumList.getSelectedValue();

        if (addTrckName.equals("") || addTrckArtist.equals(""))
        {
            outcomeArea.setText(
                    "Please make sure that you have entered a track name and an artist");
        }
        else
        {
            if (musicCollection.addTrack(addTrckName, addTrckArtist, anAlbum))
            {
                outcomeArea.setText("Track successfully added");
                displayAlbums();
                resetTextValues();
            }
            else
            {
                outcomeArea.setText("Sorry, there has been a problem");
            }

        }

    }

    private void removeTrack()
    {
        int dialogResult = optionPane.showConfirmDialog(null,
                "Do you want to remove track?", "Confirm",
                optionPane.YES_NO_OPTION, optionPane.QUESTION_MESSAGE);
        if (dialogResult == optionPane.YES_OPTION)
        {
            Album anAlbum = (Album) albumList.getSelectedValue();
            Track aTrack = (Track) trackList.getSelectedValue();
            musicCollection.removeTrack(aTrack, anAlbum);
            displayAlbums();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        albumList = new m256gui.M256JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        trackList = new m256gui.M256JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addAlbum = new javax.swing.JButton();
        addAlbumName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addAlbumArtist = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addTrackName = new javax.swing.JTextField();
        addTrackArtist = new javax.swing.JTextField();
        addTrack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        outcomeArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        albumList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        albumList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                albumListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(albumList);

        trackList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(trackList);

        jLabel1.setText("Albums");

        jLabel2.setText("Album tracks");

        addAlbum.setText("Add album");
        addAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAlbumMouseClicked(evt);
            }
        });

        addAlbumName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlbumNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Add Album");

        jLabel4.setText("Album name:");

        jLabel5.setText("Album artist:");

        jButton3.setText("Delete selected album");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Delete selected track");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel6.setText("Add Track");

        jLabel7.setText("Track name");

        jLabel8.setText("Track artist");

        addTrackName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrackNameActionPerformed(evt);
            }
        });

        addTrack.setText("Add track");
        addTrack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTrackMouseClicked(evt);
            }
        });

        outcomeArea.setColumns(20);
        outcomeArea.setRows(5);
        jScrollPane3.setViewportView(outcomeArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAlbum)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addAlbumArtist)
                                    .addComponent(addAlbumName, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                            .addComponent(jLabel5))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addContainerGap())
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(addTrackName, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                        .addComponent(addTrack)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(addTrackArtist, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                                    .addGap(28, 28, 28))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addAlbumName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(addTrackName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addAlbumArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addAlbum))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTrackArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addTrack)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAlbumNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addAlbumNameActionPerformed
    {//GEN-HEADEREND:event_addAlbumNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAlbumNameActionPerformed

    private void addTrackNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addTrackNameActionPerformed
    {//GEN-HEADEREND:event_addTrackNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrackNameActionPerformed

    private void albumListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_albumListValueChanged
    {//GEN-HEADEREND:event_albumListValueChanged
        getAlbumTracks();
    }//GEN-LAST:event_albumListValueChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton3MouseClicked
    {//GEN-HEADEREND:event_jButton3MouseClicked
        removeAlbum();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton4MouseClicked
    {//GEN-HEADEREND:event_jButton4MouseClicked
        removeTrack();
    }//GEN-LAST:event_jButton4MouseClicked

    private void addAlbumMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_addAlbumMouseClicked
    {//GEN-HEADEREND:event_addAlbumMouseClicked
        addAlbum();
    }//GEN-LAST:event_addAlbumMouseClicked

    private void addTrackMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_addTrackMouseClicked
    {//GEN-HEADEREND:event_addTrackMouseClicked
        addTrack();
    }//GEN-LAST:event_addTrackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new MusiccollectionGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAlbum;
    private javax.swing.JTextField addAlbumArtist;
    private javax.swing.JTextField addAlbumName;
    private javax.swing.JButton addTrack;
    private javax.swing.JTextField addTrackArtist;
    private javax.swing.JTextField addTrackName;
    private m256gui.M256JList albumList;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea outcomeArea;
    private m256gui.M256JList trackList;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JOptionPane optionPane;
}
